{{- if .Values.enableSparkSupport }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tonic-spark-helper
  namespace: {{ .Release.Namespace }}
  labels:
    app: tonic-spark-helper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tonic-spark-helper
  strategy: {}
  template:
    metadata:
      labels:
        app: tonic-spark-helper
    spec:
      containers:
      - env:
        - name: ENABLE_LOG_COLLECTION
          value: {{quote .Values.enableLogCollection }}
        - name: ENVIRONMENT_NAME
          value: {{ .Values.environmentName }}
        image: quay.io/tonicai/tonic_spark_helper:{{ .Values.tonicVersion }}
        imagePullPolicy: "Always"
        name: tonic-spark-helper
        ports:
        - containerPort: 5501
        resources: {}
        livenessProbe:
          httpGet:
            path: /health
            port: 5501
            scheme: HTTPS
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5501
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 10
      restartPolicy: Always
      imagePullSecrets:
      - name: tonicai-build-writer-pull-secret
      serviceAccountName: ""
{{- end }}